{
 "title": "other-latency",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(ping_durations_s_count) by (source_zone, source_node_name)) by (source_zone)",
     "legendFormat": "{{ source_zone }}"
    }
   ]
  },
  {
   "title": "Bandwith per connection (avg over downloads)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(16*1024*1024)/(sum(abs(delta(download_durations_s_sum{}[5m]))< 50) by (source_node_name, dest_node_name)/sum(abs(delta(download_durations_s_count{}[5m]))) by (source_node_name, dest_node_name))",
     "legendFormat": "{{ source_node_name }} => {{ dest_node_name }}"
    }
   ]
  },
  {
   "title": "Latencies quantile 0.5 by zones",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(ping_durations_s{quantile='0.5'} > 0) by (source_node_name, dest_node_name)",
     "legendFormat": "{{dest_node_name}} => {{ source_node_name}}"
    }
   ]
  },
  {
   "title": "Latencies quantile 0.9 by zones",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(ping_durations_s{quantile='0.9'} > 0) by (source_node_name, dest_node_name)",
     "legendFormat": "{{dest_node_name}} => {{ source_node_name}}"
    }
   ]
  },
  {
   "title": "Latencies quantile 0.99 by zones",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(ping_durations_s{quantile='0.99'} > 0) by (source_node_name, dest_node_name)",
     "legendFormat": "{{dest_node_name}} => {{ source_node_name}}"
    }
   ]
  }
 ]
}